Array.from(document.querySelectorAll(".bh-radio-label"))
    .filter((item)=>{return ['完全符合', '非常满意'].includes(item.innerText)})
    .forEach((item)=>{item.click()})
Array.from(document.querySelectorAll("input[data-x-bl='100']"))
    .forEach((item)=>{ item.checked=true })
Array.from(document.querySelectorAll("input[type='checkbox']"))
    .forEach((item)=>{ item.checked=true })
Array.from(document.getElementsByClassName("bh-txt-input__txtarea"))
    .forEach((item)=>{ item.value="教学很负责，老师辛苦了！"; })
